### ISSUE TITLE
Clean Up Repository

### ISSUE THREAD

**Issue by not-nef** [TimerX-App/TimerX#52]
The repository definitely needs some cleaning. Its just a big mess atm. A few things i suggest doing:

- Remove the `.vscode` folder since it isnt needed

- Put all the `requirements*.txt` in a single `dependencies` folder (dont forget to update the docs)

- Rename the `docs` folder to `website`, create a new folder called `docs` and put `CODE_OF_CONDUCT.md`, `CONTRIBUTING.md`, `LICENSE`, `README.md` in it

- Maybe delete the `Scripts` folder? (idk what its used for)

**Comment by im-coder-lg** [comment]
Nice idea, but I did try that. `docs` seems a simpler idea than `website` and we could add the same data of CODE_OF_CONDUCT.md, etc. in the documentation. I think the `Scripts` folder is used to make a VENV on Windows.
No use moving repo data to `docs`.
Putting all the `requirements-*.txt` together would be hard since win10toast exists only on Windows. Some modules are unavailable on Linux and macOS and it'd be better to load the required modules.

**Comment by im-coder-lg** [comment]
Maybe let's make a `cleanup` branch and clean up the entire code. I'll try reformatting the website using Prettier and try Jest(idk they call it code coverage, what's it used for?) and use `black` and other Python code formatters to format the code neatly.

**Comment by not-nef** [comment]
Nonono, you understood me wrong. We can keep the files seperate, just move them all in one folder

**Comment by sumeshir26** [comment]
> Remove the .vscode folder since it isnt needed

Yeah, will do

> Put all the requirements*.txt in a single dependencies folder (dont forget to update the docs)

No, because it is not python convention to put in in a folder

> Maybe delete the Scripts folder? (idk what its used for)

Yes, will do

**Comment by im-coder-lg** [comment]
I hate the GitHub UI. Makes it hard to locate new comments while on that page. They need to fix that.

**Comment by not-nef** [comment]
> No use moving repo data to `docs`.

Well, we would have 4 less files in the root dir

**Comment by im-coder-lg** [comment]
> Well, we would have 4 less files in the root dir

Those files _must_ be in the repo dir. Don't blame me, it's GitHub convention.

**Comment by not-nef** [comment]
> > Well, we would have 4 less files in the root dir
> 
> 
> 
> Those files _must_ be in the repo dir. Don't blame me, it's GitHub convention.

No, they dont

**Comment by not-nef** [comment]
> > > Well, we would have 4 less files in the root dir
> > 
> > 
> > 
> > Those files _must_ be in the repo dir. Don't blame me, it's GitHub convention.
> 
> No, they dont

![image](https://user-images.githubusercontent.com/83908932/149719055-e628707e-b538-4aba-b770-c5e182840d0a.png)

![image](https://user-images.githubusercontent.com/83908932/149719064-e4d93fcb-2acd-45c5-b855-763bd3a7702f.png)

![image](https://user-images.githubusercontent.com/83908932/149719069-622b0a98-bee3-4016-a4ba-c82dfb9a37b3.png)

**Comment by im-coder-lg** [comment]
Great, I'll edit this in the `cleanup` branch now.

**Comment by im-coder-lg** [comment]
Also, don't get me wrong, I am putting a collapsor via HTML so that we could save some screen space.

**Comment by not-nef** [comment]
> No, because it is not python convention to put in in a folder

wut

**Comment by not-nef** [comment]
> Also, don't get me wrong, I am putting a collapsor via HTML so that we could save some screen space.

Epic

**Comment by im-coder-lg** [comment]
Following conventions might give you a solid five-star rating since everything is organized. That's my motto. I like a neat workspace, it's a habit.

**Comment by im-coder-lg** [comment]
Moreover, the collapsor is literally this:
```html
<details>
<summary>Short title</summary>

Start details after a space to format Markdown.

End with a space.

</details>
```
Done.

**Comment by sumeshir26** [comment]
> wut

 If you see any big python repos, the requirements file is NEVER in a folder

**Comment by im-coder-lg** [comment]
They just keep them in a file and make sure they use cross-platform modules.

**Comment by not-nef** [comment]
> > wut
> 
> 
> 
>  If you see any big python repos, the requirements file is NEVER in a folder

but we have 3 of them

**Comment by im-coder-lg** [comment]
I think it's best to let them be.

**Comment by im-coder-lg** [comment]
I'm also helping here. Basically, I think cleaning up the repo would also include organizing the files, so I am also assigning this to myself.
