### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by sumeshir26** [TimerX-App/TimerX#59]
# The Problem
After running a test side-by-side of the Windows 11 clock app and TimerX of 30 Minutes, TimerX lags 22 seconds behind.
# Cause
TimerX does not use a actual timer, it just waits for a second  and then takes a few milliseconds to process it(Update `time_display`, `seconds_left`, etc .). Those milliseconds add up and cause a lag.
# Possible Solutions
- Use a Process using `multiprocessing` instead of threads to provide higher priority
- Use `time.clock` to actually count real time. A benefit of this is that TimerX will then count in milliseconds which will lead to almost-instant pausing 
- Use a `C#`function for the `timer_thread`

### @not-nef and @im-coder-lg what are your thoughts?

**Comment by not-nef** [comment]
time.clock seems like the best solution to me

**Comment by im-coder-lg** [comment]
We could try options 2 and 3, the only problem is that if you are compiling with option 3, you need C# tools. I guess that's a pain. I'd prefer option 2 since that'd make compiling easier.

**Comment by im-coder-lg** [comment]
A question - does `time.clock` consume huge chunks of RAM?

**Comment by sumeshir26** [comment]
No Idea, the last time I messed with that was over a year ago, I at that time more than making semi-polished apps, I just wanted to learn

**Comment by im-coder-lg** [comment]
But does it? Why not integrate it before Republic Day?

**Comment by sumeshir26** [comment]
I'll try

**Comment by sumeshir26** [comment]
Started work on this!

**Comment by sumeshir26** [comment]
_Closing as Resolved_
