### ISSUE TITLE
New screenshot on account of v1.0

### ISSUE THREAD

**Issue by im-coder-lg** [TimerX-App/TimerX#71]
Invoked from triage board/roadmap.

**Comment by im-coder-lg** [comment]
From the project. @sumeshir26 or @not-nef can you add a newer screenshot since 1.0 is out and UI has changed a lot?

**Comment by sumeshir26** [comment]
I'll do it

**Comment by sumeshir26** [comment]
Which one do you like?
![image](https://user-images.githubusercontent.com/68823982/151489694-6ef8cf74-7e30-4b8e-90bd-15059e525828.png)
![image](https://user-images.githubusercontent.com/68823982/151490060-3b025c71-a95c-4d44-ae5e-e191b9c3f54c.png)

**Comment by im-coder-lg** [comment]
Both look fantastic. Let's add both with light mode and dark mode text below them. Maybe like using the quote markdown syntax for Light and Dark mode. Like this?
```markdown
<div align=center>

> Quote

</div>
```

**Comment by sumeshir26** [comment]
Ok, Making A PR...

**Comment by im-coder-lg** [comment]
Closed on merge of #72.
